# variables: ARMADILLO_FOUND ARMADILLO_INCLUDE_DIRS ARMADILLO_LIBRARIES
# ARMADILLO_LIBRARY_DIRS

find_path(ARMADILLO_INCLUDE_DIR armadillo)
find_library(ARMADILLO_LIBRARY armadillo)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(ARMADILLO DEFAULT_MSG ARMADILLO_INCLUDE_DIR
                                  ARMADILLO_LIBRARY)
mark_as_advanced(ARMADILLO_INCLUDE_DIR ARMADILLO_LIBRARY)

if(ARMADILLO_FOUND)
  set(ARMADILLO_INCLUDE_DIRS ${ARMADILLO_INCLUDE_DIR})
  set(ARMADILLO_LIBRARIES ${ARMADILLO_LIBRARY})
endif()
