message(STATUS "Configuring llvm ...")

if(LLVM_INCLUDED)
  return()
endif()
set(LLVM_INCLUDED TRUE)

if(USE_INTERNAL_LLVM)
  set(LLVM_EP_DIR ${CONTRIB_ROOT_DIR}/llvm/ep)
  set(LLVM_SOURCE_DIR ${CONTRIB_ROOT_DIR}/llvm/src)
  set(LLVM_BUILD_DIR ${CONTRIB_ROOT_DIR}/llvm/build)
  set(LLVM_INSTALL_DIR ${CONTRIB_ROOT_DIR}/llvm/install)

  if(NOT EXISTS "${LLVM_SOURCE_DIR}/README.md")
    message(SEND_ERROR "Submodule llvm missing. To fix, try run: "
                       "make sync_submodule")
  endif()

  set(TMP_C_FLAGS "-pthread -fPIC")
  set(TMP_CXX_FLAGS "-pthread -fPIC")
  set(ENABLE_PROJECTS "\'openmp\\$<SEMICOLON>clang\'")

  ExternalProject_Add(
    LLVM
    PREFIX ${LLVM_EP_DIR}
    SOURCE_DIR ${LLVM_SOURCE_DIR}
    BINARY_DIR ${LLVM_BUILD_DIR}
    INSTALL_DIR ${LLVM_INSTALL_DIR}
    LOG_CONFIGURE TRUE
    LOG_BUILD TRUE
    LOG_OUTPUT_ON_FAILURE TRUE
    CONFIGURE_COMMAND
      cmake ${CMAKE_GENERATOR_FLAG} -DCMAKE_BUILD_TYPE=MinSizeRel
      -DCMAKE_INSTALL_PREFIX=${LLVM_INSTALL_DIR}
      -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
      -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER} -DCMAKE_CXX_FLAGS=${TMP_CXX_FLAGS}
      -DCMAKE_C_FLAGS=${TMP_C_FLAGS} -DLLVM_ENABLE_PROJECTS=openmp
      -DLIBOMP_ENABLE_SHARED=OFF -DOPENMP_STANDALONE_BUILD=ON
      -DOPENMP_ENABLE_LIBOMPTARGET=OFF -DLLVM_PARALLEL_COMPILE_JOBS=${NUM_CORES}
      -DLLVM_BUILD_LLVM_DYLIB=OFF -DLLVM_BUILD_TOOLS=OFF ${LLVM_SOURCE_DIR}/llvm
    BUILD_COMMAND ${GENERATOR} -j${NUM_CORES}
    INSTALL_COMMAND ${GENERATOR} -j${NUM_CORES} install)

  set(LLVM_INCLUDE_DIRS ${LLVM_INSTALL_DIR}/include)
  set(LLVM_LIBRARIES omp)
  set(LLVM_LIBRARY_DIRS ${LLVM_INSTALL_DIR}/lib)
else()

endif()

message(STATUS "Using LLVM_INCLUDE_DIRS=${LLVM_INCLUDE_DIRS}")
message(STATUS "Using LLVM_LIBRARIES=${LLVM_LIBRARIES}")
message(STATUS "Using LLVM_LIBRARY_DIRS=${LLVM_LIBRARY_DIRS}")
