name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
    steps:
    - name: Install dependencies
      run: |
        brew install automake autoconf openmpi boost
        ls /usr/local/bin
        ls /usr/local/lib
        echo "/usr/local/bin" >> $GITHUB_PATH
        echo "/usr/local/lib" >> $GITHUB_PATH
        echo "/usr/local/include" >> $GITHUB_PATH
    - name: yaml
      run: make yaml

  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y automake autoconf-archive texinfo
        sudo apt-get install -y openmpi-bin libopenmpi-dev libboost-all-dev
        ls /usr/local/bin
        ls /usr/local/lib
        echo "/usr/local/bin" >> $GITHUB_PATH
        echo "/usr/local/lib" >> $GITHUB_PATH
        echo "/usr/local/include" >> $GITHUB_PATH
    - name: yaml
      run: make yaml
  